name: love_and_care
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  json_serializable: ^6.7.0
  http: ^0.13.6
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  go_router: ^7.0.2
  intl: ^0.18.1
  timeago: ^3.4.0
  shared_preferences: ^2.1.1
  mockito: ^5.2.0
  build_runner: ^2.3.3
  internet_connection_checker: ^1.0.0+1
  sqflite: ^2.2.8+4
  uuid: ^3.0.4
  bloc_test: ^9.1.2
  http_client: ^1.5.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
